const
	gulpPugClient = require(`gulp-pug-client`),
	{
		src,
		dest,
		series,
		parallel,
		watch,
	} = require(`gulp`),
	input = `gulp/`,
	globs = {};

globs.pugClient = input + `pug-client/*.pug`;
function pugClient() {
	return src(globs.pugClient)
		.pipe(gulpPugClient())
		.pipe(dest(`public/pug-client`));
}

const build = pugClient;

async function watchFiles() {
	watch(globs.pugClient, pugClient);
}

module.exports = {
	default: parallel(build, watchFiles),
	build: build,
};
