module Main exposing (..)
main : Program () Model Msg
main =
    Platform.worker
        { init = init
        , update = update
        , subscriptions = subscriptions
        }
-- MODEL
type alias Model = ()
init : () -> ( Model, Cmd Msg )
init _ = Debug.todo "init"
-- UPDATE
type Msg = Todo
update : Msg -> Model -> ( Model, Cmd Msg )
update msg model = Debug.todo "update"
-- SUBSCRIPTIONS
subscriptions : Model -> Sub Msg
subscriptions _ = Sub.none
