# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/41aefe40-3d26-4632-9788-1fa412641c60";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/167875cb-b465-4c41-8a28-d7bcb0fe383e"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
